action: try to install `nix` before attempting to fetch bash from nixpkgs
on macOS (where `/bin/bash` is too old) we will (by default) fall back
to trying to fetch bash from nixpkgs

prior to this commit, in workflows where nix is not already installed,
this would fail because our logic that installs nix only runs after
we've found a suitable bash interpreter

because we don't actually need a modern interactive bash to check for
and install nix, we can reorder the steps to fix this

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -76,6 +76,10 @@ runs:
     # `[ ${BASH_VERSINFO[0]} -ge 4 ]` is used to check that bash has major
     # version >= 4
     #
+    # `bashForBootstrap` represents a less strict requirement: enough to check
+    # whether `nix` is installed but not necessarily new enough/with `compgen`
+    # support
+    #
     # Note: we need `continue-on-error` otherwise subsequent commands won't run
     # and we need `steps.... == 'failure'` gates on these commands so they don't
     # run when the previous test _didn't_ fail. Unfortunate but what to do.
@@ -84,8 +88,11 @@ runs:
       shell: bash
       run: |
         command -v bash || exit 1
+        echo "bashForBootstrap=$(command -v bash)" >> $GITHUB_OUTPUT
+
         type compgen &>/dev/null || exit 2
         bash -c '[ ${BASH_VERSINFO[0]} -ge 4 ]' || exit 3
+
         echo "bash=$(command -v bash)" >> $GITHUB_OUTPUT
     - id: try-hardcoded-bash
       continue-on-error: true
@@ -93,37 +100,20 @@ runs:
       shell: '/bin/bash {0}'
       run: |
         /bin/bash -c "type compgen &>/dev/null" || exit 2
+        echo "bashForBootstrap=$(command -v bash)" >> $GITHUB_OUTPUT
+
         /bin/bash -c '[ ${BASH_VERSINFO[0]} -ge 4 ]' || exit 3
 
         echo '::notice::bash not on $PATH, using /bin/bash...'
         echo "bash=/bin/bash" >> $GITHUB_OUTPUT
-    - id: try-nix-shell-bash
-      continue-on-error: true
-      if: steps.try-hardcoded-bash.outcome == 'failure'
-      shell: 'nix-shell {0}'
-      run: |
-        { nixpkgs ? import <nixpkgs> {} }: with nixpkgs; mkShell {
-          shellHook = ''
-            echo '::notice::using bash from `nixpkgs`...'
-            echo "bash=${lib.getExe bashInteractive}" >> $GITHUB_OUTPUT
-          '';
-        }
 
-    - name: "error: no bash found"
-      if: steps.try-nix-shell-bash.outcome == 'failure'
-      # Note: *not* continue on error; this is the end of the chain.
-      shell: sh
-      run: echo "::error::no suitable bash found!" && exit 4
-
-    - id: bash-path
-      shell: "${{ (steps.try-bash.outcome == 'success' && steps.try-bash.outputs.bash) || (steps.try-hardcoded-bash.outcome == 'success' && steps.try-hardcoded-bash.outputs.bash) || (steps.try-nix-shell-bash.outcome == 'success' && steps.try-nix-shell-bash.outputs.bash) || 'unreachable' }} {0}"
-      run: |
-        BASH_PATH="${{ (steps.try-bash.outcome == 'success' && steps.try-bash.outputs.bash) || (steps.try-hardcoded-bash.outcome == 'success' && steps.try-hardcoded-bash.outputs.bash) || (steps.try-nix-shell-bash.outcome == 'success' && steps.try-nix-shell-bash.outputs.bash) || 'unreachable' }}"
-        echo "bash=${BASH_PATH} --noprofile --norc -e -o pipefail {0}" >> $GITHUB_OUTPUT
-        echo "bash-binary-path=${BASH_PATH}" >> $GITHUB_OUTPUT
-
+    # Check that nix is installed/attempt to install nix:
     - id: check-for-nix
-      shell: ${{ steps.bash-path.outputs.bash }}
+      # Uses the bootstrap bash; if none was found *and* if `sh` isn't present
+      # this step will fail but we'll continue anyways just in case
+      # `install-nix-action` is able to make successfully install nix.
+      shell: "${{ (steps.try-bash.outputs.bashForBootstrap) || (steps.try-hardcoded-bash.bashForBootstrap) || 'sh' }} {0}"
+      continue-on-error: true
       run: |
         if ! command -v nix; then
           echo "nix-missing=true" >> $GITHUB_OUTPUT
@@ -149,6 +139,31 @@ runs:
       uses: cachix/install-nix-action@v22
       with:
         nix_path: nixpkgs=channel:nixos-unstable
+
+    - id: try-nix-shell-bash
+      continue-on-error: true
+      if: steps.try-hardcoded-bash.outcome == 'failure'
+      shell: 'nix-shell {0}'
+      run: |
+        { nixpkgs ? import <nixpkgs> {} }: with nixpkgs; mkShell {
+          shellHook = ''
+            echo '::notice::using bash from `nixpkgs`...'
+            echo "bash=${lib.getExe bashInteractive}" >> $GITHUB_OUTPUT
+          '';
+        }
+
+    - name: "error: no bash found"
+      if: steps.try-nix-shell-bash.outcome == 'failure'
+      # Note: *not* continue on error; this is the end of the chain.
+      shell: sh
+      run: echo "::error::no suitable bash found!" && exit 4
+
+    - id: bash-path
+      shell: "${{ (steps.try-bash.outcome == 'success' && steps.try-bash.outputs.bash) || (steps.try-hardcoded-bash.outcome == 'success' && steps.try-hardcoded-bash.outputs.bash) || (steps.try-nix-shell-bash.outcome == 'success' && steps.try-nix-shell-bash.outputs.bash) || 'unreachable' }} {0}"
+      run: |
+        BASH_PATH="${{ (steps.try-bash.outcome == 'success' && steps.try-bash.outputs.bash) || (steps.try-hardcoded-bash.outcome == 'success' && steps.try-hardcoded-bash.outputs.bash) || (steps.try-nix-shell-bash.outcome == 'success' && steps.try-nix-shell-bash.outputs.bash) || 'unreachable' }}"
+        echo "bash=${BASH_PATH} --noprofile --norc -e -o pipefail {0}" >> $GITHUB_OUTPUT
+        echo "bash-binary-path=${BASH_PATH}" >> $GITHUB_OUTPUT
 
     # Point to the vendored `nix-direnv`'s script.
     #
